### ISSUE TITLE
Annoying compilation warnings from EcologicalNetworks dependency.

### ISSUE THREAD

**Issue by iago-lito** [BecksLab/EcologicalNetworksDynamics.jl#145]
These warnings appear whenever `using EcologicalNetworksDynamics` in a fresh environment. They originate from foreign code at [PoisotLab/EcologicalNetworks.jl](https://github.com/PoisotLab/EcologicalNetworks.jl), which seems unmaintained now.

Either move from this dependency to its said sucessor: [PoisotLab/SpeciesInteractionNetworks.jl](https://github.com/PoisotLab/SpeciesInteractionNetworks.jl)

Or drop this dependency and reimplement niche/cascade models by hand.. is this everything we need it for?

**Comment by ismael-lajaaiti** [comment]
I wouldn't move to SpeciesInteractionNetworks because this package is not released yet on the Julia registry, therefore I expect it to be unstable. As we use this package only to generate niche and cascade model I suggest to recode ourselves these functions. I can give it a try.

**Comment by iago-lito** [comment]
Closed by #147.
