### ISSUE TITLE
Check Pkg installation

### ISSUE THREAD

**Issue by alaindanet** [BecksLab/EcologicalNetworksDynamics.jl#155]
1. The package requires julia v1.10 but the error message does not appear
2. Check that the package can be installed on Windows

**Comment by alaindanet** [comment]
That sounds all good!
It would be great to find a way to point the reviewers toward the CI results while staying anonymous in principle? To prove that the package works? What do you think @ismael-lajaaiti?

**Comment by iago-lito** [comment]
Relevant to the issue that errors from an incompatible version of Julia are not super-clear: https://github.com/JuliaLang/Pkg.jl/issues/3907.
