### ISSUE TITLE
Standalone usecase script

### ISSUE THREAD

**Issue by alaindanet** [BecksLab/EcologicalNetworksDynamics.jl#156]
Provide a standalone script at destination of non-julia users, that encompass:
1. a check of Julia version
2. Pkg installation
3. usecases

-----
## Snippets
1.
```
v"1.10" <= VERSION < v"2.0" || throw("Incorrect Julia version. Please install at least the julia version 1.10 at https://julialang.org/downloads/")
```

2. May be add a snippet to check if the package is already installed
```
import Pkg; Pkg.add("EcologicalNetworksDynamics")
Pkg.instantiate()
Pkg.update()
using EcologicalNetworksDynamics
```

**Comment by iago-lito** [comment]
Considering that our audience has proven not capable of doing this by themselves, I think it could be a good idea X'(

Just curious here: why do you think that `Pkg.instantiate()` and `Pkg.update()` would be necessary?

**Comment by alaindanet** [comment]
@iago-lito that sounds good!
I am not sure why `instantiate` and `update` would be necessary, probably not! I use it more as a check that everything is ok!

**Comment by iago-lito** [comment]
Hi @alaindanet. I read this is marked 'in review' but I'm not sure there is anything to review yet? Did you close it because you've written the script? :)
